/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telasProjeto;

import CRUD.CRUDPaineis;
import javax.swing.JOptionPane;

import com.mycompany.solartoyour.Usuario;

import DAO.DAO;

/**
 *
 * @author Henri
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        super("SolarToyour");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelExterno = new javax.swing.JPanel();
        jPanelInterno = new javax.swing.JPanel();
        loginTextField = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        sairButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        cadastrarLoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanelExterno.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanelExterno.setOpaque(false);
        jPanelExterno.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanelInterno.setOpaque(false);
        jPanelInterno.setPreferredSize(new java.awt.Dimension(380, 400));

        javax.swing.GroupLayout jPanelInternoLayout = new javax.swing.GroupLayout(jPanelInterno);
        jPanelInterno.setLayout(jPanelInternoLayout);
        jPanelInternoLayout.setHorizontalGroup(
            jPanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanelInternoLayout.setVerticalGroup(
            jPanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelExternoLayout = new javax.swing.GroupLayout(jPanelExterno);
        jPanelExterno.setLayout(jPanelExternoLayout);
        jPanelExternoLayout.setHorizontalGroup(
            jPanelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExternoLayout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addComponent(jPanelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExternoLayout.setVerticalGroup(
            jPanelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        loginTextField.setBackground(new java.awt.Color(204, 204, 204));
        loginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite Seu Login(Nome ou Email):", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        loginTextField.setPreferredSize(new java.awt.Dimension(270, 55));
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginTextField);
        loginTextField.setBounds(510, 160, 270, 55);

        senhaPasswordField.setBackground(new java.awt.Color(204, 204, 204));
        senhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite Sua Senha:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        senhaPasswordField.setPreferredSize(new java.awt.Dimension(270, 55));
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(510, 280, 270, 55);

        sairButton.setBackground(new java.awt.Color(7, 14, 43));
        sairButton.setForeground(new java.awt.Color(255, 255, 102));
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(550, 390, 72, 23);

        loginButton.setBackground(new java.awt.Color(7, 14, 43));
        loginButton.setForeground(new java.awt.Color(255, 255, 102));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(710, 390, 72, 23);

        cadastrarLoginButton.setBackground(new java.awt.Color(7, 14, 43));
        cadastrarLoginButton.setForeground(new java.awt.Color(255, 255, 102));
        cadastrarLoginButton.setText("Cadastrar Login");
        cadastrarLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarLoginButton);
        cadastrarLoginButton.setBounds(620, 520, 150, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaLogin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 600);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 60, 170, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ainda Nao Tem Login? Clique em Casdatrar e Crie Um!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 440, 370, 50);

        setSize(new java.awt.Dimension(816, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        //Ira Pegar a Senha,(Email e Nome) do Usuario.Por mais que Nome ou Email seja necessario.
        String login = loginTextField.getText();
        String senha = new String(senhaPasswordField.getPassword());
        //Vai Verificar se o usuario e valido

    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Aqui ao Clicar em Login(na Tela Login) 
        //O programa vai pegar o Login e Senha
        String login = loginTextField.getText();
        //Pega a senha do usuario como char[] e converte para String
        String senha = new String(senhaPasswordField.getPassword());

        try {
            Usuario usuario = new Usuario(login, login, senha);
            DAO dao = new DAO();
            if(dao.existe(usuario))
                if(usuario.getIs_admin()){
                    JOptionPane.showMessageDialog(null, "Seja Bem vindo " + usuario.getNome() + "!");
                    CRUDPaineis paineis = new CRUDPaineis();
                    paineis.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Seja Bem vindo " + usuario.getNome() + "!");
                    Menu menu = new Menu();
                    menu.setVisible(true);
                }
            else {
                JOptionPane.showMessageDialog(null, "Usuario Invalido");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.Tente Novamente Mais Tarde!");
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    private void cadastrarLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLoginButtonActionPerformed
        // Ao clicar em Cadastar Login , vai ser redirecionado para tal
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_cadastrarLoginButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarLoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelExterno;
    private javax.swing.JPanel jPanelInterno;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JButton sairButton;
    private javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration//GEN-END:variables
}
