/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telasProjeto;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menuteste
     */
    public Menu() {
        super("SolarToyour");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FazerSimulacaojButton = new javax.swing.JButton();
        VisualizarHistoricojButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PerfiljButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 80);

        FazerSimulacaojButton.setBackground(new java.awt.Color(255, 255, 102));
        FazerSimulacaojButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FazerSimulacaojButton.setText("Fazer Simulação");
        FazerSimulacaojButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FazerSimulacaojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FazerSimulacaojButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FazerSimulacaojButton);
        FazerSimulacaojButton.setBounds(20, 230, 160, 27);

        VisualizarHistoricojButton.setBackground(new java.awt.Color(255, 255, 102));
        VisualizarHistoricojButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VisualizarHistoricojButton.setText("Visualizar Histórico");
        VisualizarHistoricojButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisualizarHistoricojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarHistoricojButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VisualizarHistoricojButton);
        VisualizarHistoricojButton.setBounds(20, 270, 170, 27);

        voltarButton.setBackground(new java.awt.Color(255, 255, 51));
        voltarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(10, 530, 90, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaLogin.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 0, 800, 600);

        PerfiljButton.setBackground(new java.awt.Color(255, 255, 102));
        PerfiljButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PerfiljButton.setText("Perfil");
        PerfiljButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PerfiljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfiljButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PerfiljButton);
        PerfiljButton.setBounds(20, 320, 160, 27);

        setSize(new java.awt.Dimension(816, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FazerSimulacaojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FazerSimulacaojButtonActionPerformed
        this.dispose(); 
        resultadoSimulacao simulacao = new resultadoSimulacao();
        simulacao.setVisible(true);
        
    }//GEN-LAST:event_FazerSimulacaojButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void PerfiljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfiljButtonActionPerformed
        TelaPerfil perfil = new TelaPerfil();
        perfil.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_PerfiljButtonActionPerformed

    private void VisualizarHistoricojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarHistoricojButtonActionPerformed
        HistóricoSimulação simulacao = new HistóricoSimulação();
        simulacao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VisualizarHistoricojButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FazerSimulacaojButton;
    private javax.swing.JButton PerfiljButton;
    private javax.swing.JButton VisualizarHistoricojButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
