/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telasProjeto;

import com.mycompany.solartoyour.CalculoSimulacao;
import javax.swing.JOptionPane;

/**
 *
 * @author Henri
 */
public class resultadoSimulacao extends javax.swing.JFrame {

    /**
     * Creates new form resultadoSimulacao
     */
    public resultadoSimulacao() {
        super ("Solartoyour");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        realizarSimulacaoButton = new javax.swing.JButton();
        inserirValorDeInvestimentoTextField = new javax.swing.JTextField();
        inserirConsumoMensalEmkWhTextField = new javax.swing.JTextField();
        inserirValorDeConsumoMensalEmR$TextField = new javax.swing.JTextField();
        inserirHorasDeSolTextField = new javax.swing.JTextField();
        tarifaLocalComboBox = new javax.swing.JComboBox<>();
        selecionarPotenciaDoPainelComboBox = new javax.swing.JComboBox<>();
        resultadoSimulacaoPanel = new javax.swing.JPanel();
        retornarQuantidadeDePaineisNecessariosTextField = new javax.swing.JTextField();
        retornarEconomiaMensalTextField = new javax.swing.JTextField();
        retornarReducaoDeCO2TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        retornarROITextField = new javax.swing.JTextField();
        InserirLinkTextField = new javax.swing.JTextField();
        inserirAtributosDoPainel1TextField = new javax.swing.JTextField();
        inserirAtributosDoPainel2TextField = new javax.swing.JTextField();
        inserirLinkTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PlanoDeFundoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado Da Simulacao");
        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(1425, 207, 100, 100);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(1425, 505, 100, 100);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Simulação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 270, 70);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(670, 10, 280, 30);

        voltarButton.setBackground(new java.awt.Color(255, 255, 102));
        voltarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(0, 0, 0));
        voltarButton.setText("Voltar");
        voltarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(voltarButton);
        voltarButton.setBounds(10, 620, 72, 27);

        realizarSimulacaoButton.setBackground(new java.awt.Color(255, 255, 102));
        realizarSimulacaoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        realizarSimulacaoButton.setForeground(new java.awt.Color(0, 0, 0));
        realizarSimulacaoButton.setText("Realizar Simulação");
        realizarSimulacaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizarSimulacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarSimulacaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(realizarSimulacaoButton);
        realizarSimulacaoButton.setBounds(250, 620, 160, 27);

        inserirValorDeInvestimentoTextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirValorDeInvestimentoTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inserirValorDeInvestimentoTextField.setForeground(new java.awt.Color(0, 0, 0));
        inserirValorDeInvestimentoTextField.setBorder(null);
        inserirValorDeInvestimentoTextField.setOpaque(true);
        inserirValorDeInvestimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirValorDeInvestimentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirValorDeInvestimentoTextField);
        inserirValorDeInvestimentoTextField.setBounds(10, 100, 200, 30);

        inserirConsumoMensalEmkWhTextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirConsumoMensalEmkWhTextField.setForeground(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.setBorder(null);
        inserirConsumoMensalEmkWhTextField.setCaretColor(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inserirConsumoMensalEmkWhTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.setOpaque(true);
        inserirConsumoMensalEmkWhTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.setSelectionColor(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirConsumoMensalEmkWhTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirConsumoMensalEmkWhTextField);
        inserirConsumoMensalEmkWhTextField.setBounds(10, 240, 200, 30);

        inserirValorDeConsumoMensalEmR$TextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirValorDeConsumoMensalEmR$TextField.setForeground(new java.awt.Color(0, 0, 0));
        inserirValorDeConsumoMensalEmR$TextField.setBorder(null);
        inserirValorDeConsumoMensalEmR$TextField.setOpaque(true);
        inserirValorDeConsumoMensalEmR$TextField.setPreferredSize(new java.awt.Dimension(64, 14));
        inserirValorDeConsumoMensalEmR$TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirValorDeConsumoMensalEmR$TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirValorDeConsumoMensalEmR$TextField);
        inserirValorDeConsumoMensalEmR$TextField.setBounds(10, 170, 200, 30);

        inserirHorasDeSolTextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirHorasDeSolTextField.setForeground(new java.awt.Color(0, 0, 0));
        inserirHorasDeSolTextField.setBorder(null);
        getContentPane().add(inserirHorasDeSolTextField);
        inserirHorasDeSolTextField.setBounds(10, 300, 200, 30);

        tarifaLocalComboBox.setBackground(new java.awt.Color(204, 204, 255));
        tarifaLocalComboBox.setForeground(new java.awt.Color(0, 0, 0));
        tarifaLocalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sao Paulo/Sao Paulo" }));
        tarifaLocalComboBox.setBorder(null);
        tarifaLocalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifaLocalComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(tarifaLocalComboBox);
        tarifaLocalComboBox.setBounds(10, 370, 200, 30);

        selecionarPotenciaDoPainelComboBox.setBackground(new java.awt.Color(204, 204, 255));
        selecionarPotenciaDoPainelComboBox.setForeground(new java.awt.Color(0, 0, 0));
        selecionarPotenciaDoPainelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100W", "200W", "300W", "400W", "500W" }));
        selecionarPotenciaDoPainelComboBox.setBorder(null);
        selecionarPotenciaDoPainelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarPotenciaDoPainelComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(selecionarPotenciaDoPainelComboBox);
        selecionarPotenciaDoPainelComboBox.setBounds(10, 450, 200, 30);

        resultadoSimulacaoPanel.setBackground(new java.awt.Color(0, 0, 50));
        resultadoSimulacaoPanel.setOpaque(false);

        retornarQuantidadeDePaineisNecessariosTextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarQuantidadeDePaineisNecessariosTextField.setForeground(new java.awt.Color(0, 0, 0));
        retornarQuantidadeDePaineisNecessariosTextField.setBorder(null);
        retornarQuantidadeDePaineisNecessariosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed(evt);
            }
        });

        retornarEconomiaMensalTextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarEconomiaMensalTextField.setForeground(new java.awt.Color(0, 0, 0));
        retornarEconomiaMensalTextField.setBorder(null);
        retornarEconomiaMensalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarEconomiaMensalTextFieldActionPerformed(evt);
            }
        });

        retornarReducaoDeCO2TextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarReducaoDeCO2TextField.setForeground(new java.awt.Color(0, 0, 0));
        retornarReducaoDeCO2TextField.setBorder(null);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Aqui Estao Algumas Recomendacoes De Paines Solares. Ao Clicar no Link Voce sera Direcionado Para o Site do vendedor");
        jLabel2.setOpaque(true);

        retornarROITextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarROITextField.setForeground(new java.awt.Color(0, 0, 0));
        retornarROITextField.setBorder(null);

        InserirLinkTextField.setBackground(new java.awt.Color(204, 204, 255));
        InserirLinkTextField.setForeground(new java.awt.Color(0, 0, 0));
        InserirLinkTextField.setText("Link A ser Inserido");
        InserirLinkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirLinkTextFieldActionPerformed(evt);
            }
        });

        inserirAtributosDoPainel1TextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirAtributosDoPainel1TextField.setForeground(new java.awt.Color(0, 0, 0));

        inserirAtributosDoPainel2TextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirAtributosDoPainel2TextField.setForeground(new java.awt.Color(0, 0, 0));

        inserirLinkTextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirLinkTextField.setForeground(new java.awt.Color(0, 0, 0));
        inserirLinkTextField.setText("Link A ser Inserido");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantidade Necessarias de Paineis Solares:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Economia Mensal:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ROI (Retorno Sobre Investimento)");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reducao De CO2:");

        javax.swing.GroupLayout resultadoSimulacaoPanelLayout = new javax.swing.GroupLayout(resultadoSimulacaoPanel);
        resultadoSimulacaoPanel.setLayout(resultadoSimulacaoPanelLayout);
        resultadoSimulacaoPanelLayout.setHorizontalGroup(
            resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(InserirLinkTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resultadoSimulacaoPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(retornarQuantidadeDePaineisNecessariosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retornarEconomiaMensalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retornarROITextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13))
                            .addComponent(retornarReducaoDeCO2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserirAtributosDoPainel2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addComponent(inserirLinkTextField)
                    .addComponent(inserirAtributosDoPainel1TextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        resultadoSimulacaoPanelLayout.setVerticalGroup(
            resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(10, 10, 10)
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retornarQuantidadeDePaineisNecessariosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retornarROITextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retornarEconomiaMensalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retornarReducaoDeCO2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inserirAtributosDoPainel1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(InserirLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(inserirAtributosDoPainel2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(inserirLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        getContentPane().add(resultadoSimulacaoPanel);
        resultadoSimulacaoPanel.setBounds(480, 40, 725, 680);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor De Investimento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 120, 16);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Digite seu Consumo Mensal Em R$");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 200, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Consumo Mensal Em kWh");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 190, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Qual a Media em Horas que sua Residencia/Propriedade recebe por Dia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 270, 400, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qual a Tarifa Local Voce ira Usar?");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 350, 210, 14);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qual potencia de Painel voce ira Usar?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 430, 240, 14);

        PlanoDeFundoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PlanoDeFundo5.jpg"))); // NOI18N
        getContentPane().add(PlanoDeFundoLabel);
        PlanoDeFundoLabel.setBounds(0, -10, 1350, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirLinkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirLinkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirLinkTextFieldActionPerformed

    private void inserirValorDeInvestimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirValorDeInvestimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirValorDeInvestimentoTextFieldActionPerformed

    private void inserirValorDeConsumoMensalEmR$TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirValorDeConsumoMensalEmR$TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirValorDeConsumoMensalEmR$TextFieldActionPerformed

    private void tarifaLocalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifaLocalComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifaLocalComboBoxActionPerformed

    private void realizarSimulacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarSimulacaoButtonActionPerformed
       
        try{
            //Como sao Varios Double E enecesario pasar de De String para Double//
            
        //Calcular Quantidade de paineis/   
        String txtConsumo = inserirValorDeConsumoMensalEmR$TextField.getText().replace(",", ".");    // Aqui e so para trocar , por ponto pois o parseDouble nAo reconhe pelo jeito//
        double consumoMensal = Double.parseDouble(txtConsumo);
        String txtPotencia = selecionarPotenciaDoPainelComboBox.getSelectedItem().toString(); //Tive que pesquisar essa po**a pqp //
        double potenciaPainel = Double.parseDouble(txtPotencia);
        
        double quantidadeP = CalculoSimulacao.quantidadePaineis ( consumoMensal,potenciaPainel);
        
        retornarQuantidadeDePaineisNecessariosTextField.setText("Voce Precisara de :"+ quantidadeP);
        }catch(Exception e){
            retornarQuantidadeDePaineisNecessariosTextField.setText("Deu Algo de errado nos Calculos:");
            
        }
        
    }//GEN-LAST:event_realizarSimulacaoButtonActionPerformed

        
        
    private void retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed

    private void selecionarPotenciaDoPainelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarPotenciaDoPainelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarPotenciaDoPainelComboBoxActionPerformed

    private void inserirConsumoMensalEmkWhTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirConsumoMensalEmkWhTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirConsumoMensalEmkWhTextFieldActionPerformed

    private void retornarEconomiaMensalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarEconomiaMensalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retornarEconomiaMensalTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultadoSimulacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InserirLinkTextField;
    private javax.swing.JLabel PlanoDeFundoLabel;
    private javax.swing.JTextField inserirAtributosDoPainel1TextField;
    private javax.swing.JTextField inserirAtributosDoPainel2TextField;
    private javax.swing.JTextField inserirConsumoMensalEmkWhTextField;
    private javax.swing.JTextField inserirHorasDeSolTextField;
    private javax.swing.JTextField inserirLinkTextField;
    private javax.swing.JTextField inserirValorDeConsumoMensalEmR$TextField;
    private javax.swing.JTextField inserirValorDeInvestimentoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton realizarSimulacaoButton;
    private javax.swing.JPanel resultadoSimulacaoPanel;
    private javax.swing.JTextField retornarEconomiaMensalTextField;
    private javax.swing.JTextField retornarQuantidadeDePaineisNecessariosTextField;
    private javax.swing.JTextField retornarROITextField;
    private javax.swing.JTextField retornarReducaoDeCO2TextField;
    private javax.swing.JComboBox<String> selecionarPotenciaDoPainelComboBox;
    private javax.swing.JComboBox<String> tarifaLocalComboBox;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
//