/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telasProjeto;

import com.mycompany.solartoyour.CalculoSimulacao;
import javax.swing.JOptionPane;

/**
 *
 * @author Henri
 */
public class resultadoSimulacao extends javax.swing.JFrame {

    /**
     * Creates new form resultadoSimulacao
     */
    public resultadoSimulacao() {
        super ("Solartoyour");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        realizarSimulacaoButton = new javax.swing.JButton();
        inserirValorDeInvestimentoTextField = new javax.swing.JTextField();
        inserirConsumoMensalEmkWhTextField = new javax.swing.JTextField();
        inserirValorDeConsumoMensalEmR$TextField = new javax.swing.JTextField();
        inserirHorasDeSolTextField = new javax.swing.JTextField();
        selecionarPotenciaDoPainelComboBox = new javax.swing.JComboBox<>();
        resultadoSimulacaoPanel = new javax.swing.JPanel();
        retornarQuantidadeDePaineisNecessariosTextField = new javax.swing.JTextField();
        retornarEconomiaMensalTextField = new javax.swing.JTextField();
        retornarReducaoDeCO2TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        retornarROITextField = new javax.swing.JTextField();
        InserirLinkTextField = new javax.swing.JTextField();
        inserirAtributosDoPainel1TextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PlanoDeFundoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado Da Simulacao");
        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(1425, 207, 100, 100);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(1425, 505, 100, 100);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Simulação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 270, 70);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(670, 10, 280, 30);

        voltarButton.setBackground(new java.awt.Color(255, 255, 102));
        voltarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(10, 620, 90, 27);

        realizarSimulacaoButton.setBackground(new java.awt.Color(255, 255, 102));
        realizarSimulacaoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        realizarSimulacaoButton.setText("Realizar Simulação");
        realizarSimulacaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizarSimulacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarSimulacaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(realizarSimulacaoButton);
        realizarSimulacaoButton.setBounds(250, 620, 180, 27);

        inserirValorDeInvestimentoTextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirValorDeInvestimentoTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inserirValorDeInvestimentoTextField.setBorder(null);
        inserirValorDeInvestimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirValorDeInvestimentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirValorDeInvestimentoTextField);
        inserirValorDeInvestimentoTextField.setBounds(10, 100, 200, 30);

        inserirConsumoMensalEmkWhTextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirConsumoMensalEmkWhTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inserirConsumoMensalEmkWhTextField.setBorder(null);
        inserirConsumoMensalEmkWhTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inserirConsumoMensalEmkWhTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.setSelectionColor(new java.awt.Color(0, 0, 0));
        inserirConsumoMensalEmkWhTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirConsumoMensalEmkWhTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirConsumoMensalEmkWhTextField);
        inserirConsumoMensalEmkWhTextField.setBounds(10, 240, 200, 30);

        inserirValorDeConsumoMensalEmR$TextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirValorDeConsumoMensalEmR$TextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inserirValorDeConsumoMensalEmR$TextField.setBorder(null);
        inserirValorDeConsumoMensalEmR$TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirValorDeConsumoMensalEmR$TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirValorDeConsumoMensalEmR$TextField);
        inserirValorDeConsumoMensalEmR$TextField.setBounds(10, 170, 200, 30);

        inserirHorasDeSolTextField.setBackground(new java.awt.Color(204, 204, 255));
        inserirHorasDeSolTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inserirHorasDeSolTextField.setBorder(null);
        inserirHorasDeSolTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirHorasDeSolTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(inserirHorasDeSolTextField);
        inserirHorasDeSolTextField.setBounds(10, 300, 200, 30);

        selecionarPotenciaDoPainelComboBox.setBackground(new java.awt.Color(204, 204, 255));
        selecionarPotenciaDoPainelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "300", "400", "500" }));
        selecionarPotenciaDoPainelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarPotenciaDoPainelComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(selecionarPotenciaDoPainelComboBox);
        selecionarPotenciaDoPainelComboBox.setBounds(10, 380, 200, 30);

        resultadoSimulacaoPanel.setBackground(new java.awt.Color(0, 0, 50));
        resultadoSimulacaoPanel.setOpaque(false);

        retornarQuantidadeDePaineisNecessariosTextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarQuantidadeDePaineisNecessariosTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        retornarQuantidadeDePaineisNecessariosTextField.setBorder(null);
        retornarQuantidadeDePaineisNecessariosTextField.setEnabled(false);
        retornarQuantidadeDePaineisNecessariosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed(evt);
            }
        });

        retornarEconomiaMensalTextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarEconomiaMensalTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        retornarEconomiaMensalTextField.setBorder(null);
        retornarEconomiaMensalTextField.setEnabled(false);
        retornarEconomiaMensalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarEconomiaMensalTextFieldActionPerformed(evt);
            }
        });

        retornarReducaoDeCO2TextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarReducaoDeCO2TextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        retornarReducaoDeCO2TextField.setBorder(null);
        retornarReducaoDeCO2TextField.setEnabled(false);
        retornarReducaoDeCO2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarReducaoDeCO2TextFieldActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText(" Aqui Estao Algumas Recomendacoes De Paines Solares. Ao Clicar no Link Voce sera Direcionado Para o Site do vendedor");
        jLabel2.setOpaque(true);

        retornarROITextField.setBackground(new java.awt.Color(204, 204, 255));
        retornarROITextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        retornarROITextField.setBorder(null);
        retornarROITextField.setEnabled(false);
        retornarROITextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarROITextFieldActionPerformed(evt);
            }
        });

        InserirLinkTextField.setBackground(new java.awt.Color(204, 204, 255));
        InserirLinkTextField.setText("Link A ser Inserido");
        InserirLinkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirLinkTextFieldActionPerformed(evt);
            }
        });

        inserirAtributosDoPainel1TextField.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantidade Necessarias de Paineis Solares:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Economia Mensal:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ROI (Retorno Sobre Investimento)");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reducao De CO2:");

        javax.swing.GroupLayout resultadoSimulacaoPanelLayout = new javax.swing.GroupLayout(resultadoSimulacaoPanel);
        resultadoSimulacaoPanel.setLayout(resultadoSimulacaoPanelLayout);
        resultadoSimulacaoPanelLayout.setHorizontalGroup(
            resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InserirLinkTextField)
                    .addComponent(inserirAtributosDoPainel1TextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resultadoSimulacaoPanelLayout.createSequentialGroup()
                        .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resultadoSimulacaoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(retornarROITextField, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                    .addComponent(jLabel13)
                                    .addComponent(retornarReducaoDeCO2TextField)
                                    .addComponent(retornarEconomiaMensalTextField)
                                    .addComponent(retornarQuantidadeDePaineisNecessariosTextField)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        resultadoSimulacaoPanelLayout.setVerticalGroup(
            resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(retornarQuantidadeDePaineisNecessariosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retornarEconomiaMensalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retornarROITextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retornarReducaoDeCO2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(inserirAtributosDoPainel1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(InserirLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        getContentPane().add(resultadoSimulacaoPanel);
        resultadoSimulacaoPanel.setBounds(480, 40, 725, 680);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor De Investimento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 120, 16);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Digite o Valor da sua Conta de Energia:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 200, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Consumo Mensal Em kWh");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 190, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Qual a Media em Horas que sua Residencia/Propriedade recebe por Dia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 270, 400, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qual potencia de Painel voce ira Usar?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 350, 240, 14);

        PlanoDeFundoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PlanoDeFundo5.jpg"))); // NOI18N
        getContentPane().add(PlanoDeFundoLabel);
        PlanoDeFundoLabel.setBounds(0, -10, 1350, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirLinkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirLinkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirLinkTextFieldActionPerformed

    private void inserirValorDeInvestimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirValorDeInvestimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirValorDeInvestimentoTextFieldActionPerformed

    private void inserirValorDeConsumoMensalEmR$TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirValorDeConsumoMensalEmR$TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirValorDeConsumoMensalEmR$TextFieldActionPerformed

    private void realizarSimulacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarSimulacaoButtonActionPerformed
       
        try{
            //Como sao Varios Double E enecesario pasar de De String para Double//
            
        //Calcular Quantidade de paineis/   
        String txtConsumo = inserirConsumoMensalEmkWhTextField.getText().replace(",", ".");    // Aqui e so para trocar , por ponto pois o parseDouble nAo reconhe pelo jeito//
        double consumoMensal = Double.parseDouble(txtConsumo);
        String txtPotencia = selecionarPotenciaDoPainelComboBox.getSelectedItem().toString(); //Tive que pesquisar essa po**a pqp //
        double potenciaPainel = Double.parseDouble(txtPotencia);
        String txthorasSol = inserirHorasDeSolTextField.getText().replace(",",".");
        double HorasDeSol = Double.parseDouble(txthorasSol);
        String txtvalorDaConta = inserirValorDeConsumoMensalEmR$TextField.getText().replace(",",".");
        double valorConta = Double.parseDouble(txtvalorDaConta);
        String txtInvestimento = inserirValorDeInvestimentoTextField.getText().replace(",",".");
        double investimentoROI = Double.parseDouble(txtInvestimento);
        
        
        
        double quantidadeP = CalculoSimulacao.quantidadePaineis ( consumoMensal,potenciaPainel,HorasDeSol);
        double economiaMensal = CalculoSimulacao.economiaMensal( valorConta,consumoMensal,quantidadeP,potenciaPainel,HorasDeSol);
        double cO2 = CalculoSimulacao.reducaoCO2(consumoMensal);
        double roi = CalculoSimulacao.roi(investimentoROI, economiaMensal);
        
        retornarQuantidadeDePaineisNecessariosTextField.setText("Voce Precisara de :" + quantidadeP + "Paineis");
        retornarEconomiaMensalTextField.setText("Voce Tera Uma Economia de :"  + economiaMensal + "R$");
        retornarReducaoDeCO2TextField.setText("Voce Vai Gerar uma Redecucao de CO2 de : " + cO2 +"kg" + "Por Ano!");
        retornarROITextField.setText("Seu Investimento tera um retorno em :" + roi + "meses");
        
        
        }catch(Exception e){
            retornarQuantidadeDePaineisNecessariosTextField.setText("Deu Algo de errado nos Calculos:");
            retornarEconomiaMensalTextField.setText("Deu Algo de errado nos Calculos");
            
        }
        
    }//GEN-LAST:event_realizarSimulacaoButtonActionPerformed

        
        
    private void retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retornarQuantidadeDePaineisNecessariosTextFieldActionPerformed

    private void selecionarPotenciaDoPainelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarPotenciaDoPainelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarPotenciaDoPainelComboBoxActionPerformed

    private void inserirConsumoMensalEmkWhTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirConsumoMensalEmkWhTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirConsumoMensalEmkWhTextFieldActionPerformed

    private void retornarEconomiaMensalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarEconomiaMensalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retornarEconomiaMensalTextFieldActionPerformed

    private void inserirHorasDeSolTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirHorasDeSolTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirHorasDeSolTextFieldActionPerformed

    private void retornarReducaoDeCO2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarReducaoDeCO2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retornarReducaoDeCO2TextFieldActionPerformed

    private void retornarROITextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarROITextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retornarROITextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultadoSimulacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InserirLinkTextField;
    private javax.swing.JLabel PlanoDeFundoLabel;
    private javax.swing.JTextField inserirAtributosDoPainel1TextField;
    private javax.swing.JTextField inserirConsumoMensalEmkWhTextField;
    private javax.swing.JTextField inserirHorasDeSolTextField;
    private javax.swing.JTextField inserirValorDeConsumoMensalEmR$TextField;
    private javax.swing.JTextField inserirValorDeInvestimentoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton realizarSimulacaoButton;
    private javax.swing.JPanel resultadoSimulacaoPanel;
    private javax.swing.JTextField retornarEconomiaMensalTextField;
    private javax.swing.JTextField retornarQuantidadeDePaineisNecessariosTextField;
    private javax.swing.JTextField retornarROITextField;
    private javax.swing.JTextField retornarReducaoDeCO2TextField;
    private javax.swing.JComboBox<String> selecionarPotenciaDoPainelComboBox;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
//