/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telasProjeto;

/**
 *
 * @author Henri
 */
public class resultadoSimulacao extends javax.swing.JFrame {

    /**
     * Creates new form resultadoSimulacao
     */
    public resultadoSimulacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        questionarioSimulacaoPanel = new javax.swing.JPanel();
        inserirConsumoMensalEmkWhTextField = new javax.swing.JTextField();
        inserirValorDeInvestimentoTextField = new javax.swing.JTextField();
        inserirHorasDeSolTextField = new javax.swing.JTextField();
        selecionarPotenciaDoPainelComboBox = new javax.swing.JComboBox<>();
        tarifaLocalComboBox = new javax.swing.JComboBox<>();
        inserirValorDeConsumoMensalEmR$TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        realizarSimulacaoButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        resultadoSimulacaoPanel = new javax.swing.JPanel();
        retornarQuantidadeDePaineisNecessariosTextField = new javax.swing.JTextField();
        retornarEconomiaMensalTextField = new javax.swing.JTextField();
        retornarReducaoDeCO2TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        retornarROITextField = new javax.swing.JTextField();
        InserirLinkTextField = new javax.swing.JTextField();
        inserirLinkTextField = new javax.swing.JTextField();
        SeparadorDeLinha = new javax.swing.JSeparator();
        inserirAtributosDoPainel1TextField = new javax.swing.JTextField();
        inserirAtributosDoPainel2TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado Da Simulacao");
        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        questionarioSimulacaoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Usuario"));

        inserirConsumoMensalEmkWhTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo Mensal Em kWh"));

        inserirValorDeInvestimentoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor de Investimento"));
        inserirValorDeInvestimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirValorDeInvestimentoTextFieldActionPerformed(evt);
            }
        });

        inserirHorasDeSolTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantas Horas em Media Sua Propriedade Recebe de Luz Solar?"));

        selecionarPotenciaDoPainelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100W", "200W", "300W", "400W", "500W" }));
        selecionarPotenciaDoPainelComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Qul A Potencia Do Painel Gostaria de Usar?"));

        tarifaLocalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sao Paulo/Sao Paulo" }));
        tarifaLocalComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Qual Tarifa Local Voce Ira Usar?"));

        inserirValorDeConsumoMensalEmR$TextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor de Consumo Mensal Em R$ :"));

        javax.swing.GroupLayout questionarioSimulacaoPanelLayout = new javax.swing.GroupLayout(questionarioSimulacaoPanel);
        questionarioSimulacaoPanel.setLayout(questionarioSimulacaoPanelLayout);
        questionarioSimulacaoPanelLayout.setHorizontalGroup(
            questionarioSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionarioSimulacaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionarioSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecionarPotenciaDoPainelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inserirValorDeConsumoMensalEmR$TextField)
                    .addComponent(tarifaLocalComboBox, 0, 359, Short.MAX_VALUE)
                    .addComponent(inserirHorasDeSolTextField)
                    .addGroup(questionarioSimulacaoPanelLayout.createSequentialGroup()
                        .addGroup(questionarioSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inserirConsumoMensalEmkWhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserirValorDeInvestimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        questionarioSimulacaoPanelLayout.setVerticalGroup(
            questionarioSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionarioSimulacaoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(inserirValorDeInvestimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inserirValorDeConsumoMensalEmR$TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inserirConsumoMensalEmkWhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inserirHorasDeSolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tarifaLocalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecionarPotenciaDoPainelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText(" Simulacao");

        realizarSimulacaoButton.setText("Realizar Simulacao");

        voltarButton.setText("Voltar");

        resultadoSimulacaoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado Da Simulacao"));

        retornarQuantidadeDePaineisNecessariosTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade de Paineis Necessarios:"));

        retornarEconomiaMensalTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Economia Mensal:"));

        retornarReducaoDeCO2TextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Reducao de CO2"));

        jLabel2.setText("Aqui Estao Algumas Recomendacoes De Paines Solares. Ao Clicar no Link Voce sera Direcionado Para o Site do vendedor");

        retornarROITextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ROI(Retorno Sobre Investimento)"));

        InserirLinkTextField.setText("Link A ser Inserido");
        InserirLinkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirLinkTextFieldActionPerformed(evt);
            }
        });

        inserirLinkTextField.setText("Link A ser Inserido");

        javax.swing.GroupLayout resultadoSimulacaoPanelLayout = new javax.swing.GroupLayout(resultadoSimulacaoPanel);
        resultadoSimulacaoPanel.setLayout(resultadoSimulacaoPanelLayout);
        resultadoSimulacaoPanelLayout.setHorizontalGroup(
            resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InserirLinkTextField)
                    .addComponent(inserirLinkTextField)
                    .addComponent(SeparadorDeLinha)
                    .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                        .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                                            .addComponent(retornarQuantidadeDePaineisNecessariosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(57, 57, 57)
                                            .addComponent(retornarROITextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                                            .addComponent(retornarEconomiaMensalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(retornarReducaoDeCO2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(inserirAtributosDoPainel1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultadoSimulacaoPanelLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(inserirAtributosDoPainel2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        resultadoSimulacaoPanelLayout.setVerticalGroup(
            resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoSimulacaoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retornarQuantidadeDePaineisNecessariosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retornarROITextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(resultadoSimulacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retornarEconomiaMensalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retornarReducaoDeCO2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SeparadorDeLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(inserirAtributosDoPainel1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InserirLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(inserirAtributosDoPainel2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(inserirLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(voltarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(realizarSimulacaoButton)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(questionarioSimulacaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)))
                .addComponent(resultadoSimulacaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(questionarioSimulacaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(realizarSimulacaoButton)
                                .addComponent(voltarButton)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(53, Short.MAX_VALUE)
                            .addComponent(resultadoSimulacaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirLinkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirLinkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirLinkTextFieldActionPerformed

    private void inserirValorDeInvestimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirValorDeInvestimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirValorDeInvestimentoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultadoSimulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultadoSimulacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InserirLinkTextField;
    private javax.swing.JSeparator SeparadorDeLinha;
    private javax.swing.JTextField inserirAtributosDoPainel1TextField;
    private javax.swing.JTextField inserirAtributosDoPainel2TextField;
    private javax.swing.JTextField inserirConsumoMensalEmkWhTextField;
    private javax.swing.JTextField inserirHorasDeSolTextField;
    private javax.swing.JTextField inserirLinkTextField;
    private javax.swing.JTextField inserirValorDeConsumoMensalEmR$TextField;
    private javax.swing.JTextField inserirValorDeInvestimentoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel questionarioSimulacaoPanel;
    private javax.swing.JButton realizarSimulacaoButton;
    private javax.swing.JPanel resultadoSimulacaoPanel;
    private javax.swing.JTextField retornarEconomiaMensalTextField;
    private javax.swing.JTextField retornarQuantidadeDePaineisNecessariosTextField;
    private javax.swing.JTextField retornarROITextField;
    private javax.swing.JTextField retornarReducaoDeCO2TextField;
    private javax.swing.JComboBox<String> selecionarPotenciaDoPainelComboBox;
    private javax.swing.JComboBox<String> tarifaLocalComboBox;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
