/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUD;
import DAO.DAOPainel;
import com.mycompany.solartoyour.Paineis;
import javax.swing.JOptionPane;





/**
 *
 * @author Henri
 */
public class AtualizarPaineis extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarPaineis
     */
    public AtualizarPaineis() {
        super("Solartoyour");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdAtualizar = new javax.swing.JTextField();
        txtModeloAtualizar = new javax.swing.JTextField();
        txtDescricaoAtualizar = new javax.swing.JTextField();
        txtPrecoAtualizar = new javax.swing.JTextField();
        btnVoltarAtualizar = new javax.swing.JButton();
        btnConfirmarAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        txtIdAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Id:"));
        txtIdAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAtualizarActionPerformed(evt);
            }
        });

        txtModeloAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo:"));
        txtModeloAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloAtualizarActionPerformed(evt);
            }
        });

        txtDescricaoAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Descricao:")));
        txtDescricaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoAtualizarActionPerformed(evt);
            }
        });

        txtPrecoAtualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço:"));

        btnVoltarAtualizar.setBackground(new java.awt.Color(7, 14, 43));
        btnVoltarAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltarAtualizar.setForeground(new java.awt.Color(255, 255, 102));
        btnVoltarAtualizar.setText("Voltar");
        btnVoltarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAtualizarActionPerformed(evt);
            }
        });

        btnConfirmarAtualizar.setBackground(new java.awt.Color(7, 14, 43));
        btnConfirmarAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmarAtualizar.setForeground(new java.awt.Color(255, 255, 102));
        btnConfirmarAtualizar.setText("Confirmar");
        btnConfirmarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Atualizar Paineis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnVoltarAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarAtualizar)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtIdAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtModeloAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescricaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtPrecoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltarAtualizar)
                    .addComponent(btnConfirmarAtualizar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 50, 700, 500);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaLogin.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 420, 600);

        setSize(new java.awt.Dimension(816, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloAtualizarActionPerformed

    private void txtDescricaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoAtualizarActionPerformed

    private void btnVoltarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAtualizarActionPerformed
        CRUDPaineis paineis = new CRUDPaineis();
        paineis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarAtualizarActionPerformed

    private void btnConfirmarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarAtualizarActionPerformed
        //Aqui o programa ira pegar o ID,Modelo,Descricao e Preco que irao ser atualizados no BD//
        int Id_paineis = Integer.parseInt(txtIdAtualizar.getText());
        String Modelo = txtModeloAtualizar.getText();
        String Descricao = txtDescricaoAtualizar.getText();
        double preco = Double.parseDouble(txtPrecoAtualizar.getText());
        
        try{
            Paineis painel = new Paineis(Modelo,Descricao,preco,Id_paineis);
            DAOPainel dao = new DAOPainel();
            dao.atualizarPainel(painel);
            JOptionPane.showMessageDialog(null,"Painel Atualizado Com Sucesso");                    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Painel Nao Atualizado");
            
        }
        
        
        
    }//GEN-LAST:event_btnConfirmarAtualizarActionPerformed

    private void txtIdAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarPaineis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarAtualizar;
    private javax.swing.JButton btnVoltarAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescricaoAtualizar;
    private javax.swing.JTextField txtIdAtualizar;
    private javax.swing.JTextField txtModeloAtualizar;
    private javax.swing.JTextField txtPrecoAtualizar;
    // End of variables declaration//GEN-END:variables
}
