/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUD;

import telasProjeto.Login;
import telasProjeto.Menu;

/**
 *
 * @author Henri
 */
public class CRUDPaineis extends javax.swing.JFrame {

    /**
     * Creates new form CRUDPaineis
     */
    public CRUDPaineis() {
        super("Gerenciador de Paineis Solares");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInserirPainelSolar = new javax.swing.JButton();
        btnExcluirPainelSolar = new javax.swing.JButton();
        btnAtualizarPainelSolar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        btnInserirPainelSolar.setBackground(new java.awt.Color(255, 255, 102));
        btnInserirPainelSolar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnInserirPainelSolar.setText("Inserir");
        btnInserirPainelSolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInserirPainelSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirPainelSolarActionPerformed(evt);
            }
        });

        btnExcluirPainelSolar.setBackground(new java.awt.Color(255, 255, 102));
        btnExcluirPainelSolar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluirPainelSolar.setText("Excluir");
        btnExcluirPainelSolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirPainelSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPainelSolarActionPerformed(evt);
            }
        });

        btnAtualizarPainelSolar.setBackground(new java.awt.Color(255, 255, 102));
        btnAtualizarPainelSolar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAtualizarPainelSolar.setText("Atualizar");
        btnAtualizarPainelSolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarPainelSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarPainelSolarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gerenciar Paineis Solares");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluirPainelSolar)
                        .addGap(156, 156, 156)
                        .addComponent(btnAtualizarPainelSolar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserirPainelSolar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirPainelSolar)
                    .addComponent(btnAtualizarPainelSolar)
                    .addComponent(btnInserirPainelSolar))
                .addGap(108, 108, 108))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 30, 551, 530);

        btnMenu.setBackground(new java.awt.Color(255, 255, 102));
        btnMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(660, 530, 90, 30);

        btnVoltar1.setBackground(new java.awt.Color(255, 255, 102));
        btnVoltar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar1);
        btnVoltar1.setBounds(20, 540, 80, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ProjetoNoCanva.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        setSize(new java.awt.Dimension(816, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //Voltar para a tela de Login
        Menu menu = new Menu();
        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnInserirPainelSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirPainelSolarActionPerformed
        InserirPaineis create = new InserirPaineis();
        create.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInserirPainelSolarActionPerformed

    private void btnAtualizarPainelSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarPainelSolarActionPerformed
        AtualizarPaineis update = new AtualizarPaineis();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtualizarPainelSolarActionPerformed

    private void btnExcluirPainelSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPainelSolarActionPerformed
        DeletarPaineis delete = new DeletarPaineis();
        delete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExcluirPainelSolarActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        Login login = new Login();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDPaineis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDPaineis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarPainelSolar;
    private javax.swing.JButton btnExcluirPainelSolar;
    private javax.swing.JButton btnInserirPainelSolar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
